#!/usr/bin/env bash

if [ -d world ]; then
    # World exist. Will upload
    bin/rclone -v sync world drive:/world
else
    # No world exist. Will download
    bin/rclone -v sync drive:/world world
fi
